In [22]:
import pandas as pd
import numpy as np
import pickle

In [23]:
dict = pickle.load(open('./nums.pickle', 'rb'))

print(dict)

{'x': [[0.30856645107269287, 0.4404051601886749, 0.4783312976360321, 0.3506532311439514, 0.5713383555412292, 0.2800399363040924, 0.6568611860275269, 0.2228333204984665, 0.7050708532333374, 0.16585487127304077, 0.37277090549468994, 0.05312109366059303, 0.5563411712646484, 0.05247265473008156, 0.6372237205505371, 0.1110089048743248, 0.6732429265975952, 0.16312110424041748, 0.3408030867576599, 0.05112141743302345, 0.5605214834213257, 0.046451542526483536, 0.6447958946228027, 0.11859238147735596, 0.6821951866149902, 0.18563508987426758, 0.3304286599159241, 0.08111432194709778, 0.5457594990730286, 0.08509521931409836, 0.627433180809021, 0.15882761776447296, 0.6673403978347778, 0.22786425054073334, 0.3406458795070648, 0.13989344239234924, 0.5113548636436462, 0.15263661742210388, 0.5877396464347839, 0.20239095389842987, 0.632606029510498, 0.24779368937015533], [0.32869505882263184, 0.4509913921356201, 0.48894837498664856, 0.3738640546798706, 0.5774572491645813, 0.2954217195510864, 0.654487311

In [24]:
x = np.asarray(dict['x'])
labels = np.asarray(dict['labels'])

In [25]:
from sklearn.preprocessing import LabelEncoder
label_b = LabelEncoder()
labels = label_b.fit_transform(labels)

print(x.shape)
print(labels)

(632, 42)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7
 7 7 7 7 7 7 7 

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, labels, train_size= 0.8, random_state = 0)

In [27]:
print(x_train)

[[0.56552178 0.85817659 0.65815288 ... 0.43596521 0.39650673 0.47295874]
 [0.63283205 0.79883617 0.7464155  ... 0.30336463 0.23084453 0.24495223]
 [0.4013128  0.75555158 0.57184964 ... 0.24650328 0.74490321 0.27032384]
 ...
 [0.36699274 0.90021276 0.51305169 ... 0.57986486 0.28755492 0.63922036]
 [0.50421214 0.83052719 0.61958671 ... 0.29578406 0.2696445  0.23267643]
 [0.56462121 0.83381796 0.67919111 ... 0.27630728 0.22944769 0.20269889]]


In [28]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, Dropout
batch_size = 32
num_classes = 10
epochs = 10

In [36]:
import tensorflow as tf

# model = Sequential()
# model.add(Conv2D(64, kernel_size = (3, 3), activation = 'relu'))
# model.add(MaxPooling2D(pool_size= (2, 2)))

# model.add(Conv2D(64, kernel_size = (3, 3), activation = 'relu'))
# model.add(MaxPooling2D(pool_size= (2, 2)))

# model.add(Conv2D(64, kernel_size = (3, 3), activation = 'relu'))
# model.add(MaxPooling2D(pool_size= (2, 2)))

# model.add(Dense(128, activation = 'relu'))

# model.add(Dense(num_classes, activation = 'softmax'))

model = Sequential([
    Dense(64, activation='relu', input_shape=(len(x[0]),)),
    Dense(64, activation='relu'),
    Dense(32, activation='relu'),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')  # num_classes is the number of ASL signs
])

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 64)                2752      
                                                                 
 dense_15 (Dense)            (None, 64)                4160      
                                                                 
 dense_16 (Dense)            (None, 32)                2080      
                                                                 
 dense_17 (Dense)            (None, 32)                1056      
                                                                 
 dense_18 (Dense)            (None, 10)                330       
                                                                 
Total params: 10378 (40.54 KB)
Trainable params: 10378 (40.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [37]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [39]:
trained_model = model.fit(x_train, y_train, validation_data = (x_test, y_test), epochs = epochs, batch_size=batch_size)

Epoch 1/10
16/16 [==============================] - 0s 7ms/step - loss: 0.5343 - accuracy: 0.8634 - val_loss: 0.4308 - val_accuracy: 0.9291
Epoch 2/10
16/16 [==============================] - 0s 4ms/step - loss: 0.4545 - accuracy: 0.9485 - val_loss: 0.3710 - val_accuracy: 0.9291
Epoch 3/10
16/16 [==============================] - 0s 3ms/step - loss: 0.4065 - accuracy: 0.9287 - val_loss: 0.3367 - val_accuracy: 0.9843
Epoch 4/10
16/16 [==============================] - 0s 3ms/step - loss: 0.3610 - accuracy: 0.9564 - val_loss: 0.2947 - val_accuracy: 0.9843
Epoch 5/10
16/16 [==============================] - 0s 3ms/step - loss: 0.3162 - accuracy: 0.9624 - val_loss: 0.2539 - val_accuracy: 0.9764
Epoch 6/10
16/16 [==============================] - 0s 3ms/step - loss: 0.2862 - accuracy: 0.9564 - val_loss: 0.2679 - val_accuracy: 0.9685
Epoch 7/10
16/16 [==============================] - 0s 4ms/step - loss: 0.2742 - accuracy: 0.9644 - val_loss: 0.2177 - val_accuracy: 0.9843
Epoch 8/10
16/16 [==

In [46]:
model.save('test_nums.keras')

In [2]:
import tensorflow as tf
model = tf.keras.models.load_model('test.keras')
# trained_model = model

In [3]:
Labels_dict = {
        0 : 'A',
        1 : 'B',
        2 : 'C',
        3 : 'D',
        4 : 'E',
        5 : 'F',
        6 : 'G',
        7 : 'H',
        8 : 'I',
        9 : 'J',
        10 : 'K',
        11 : 'L',
        12 : 'M',
        13 : 'N',
        14 : 'O',
        15 : 'P',
        16 : 'Q',
        17 : 'R',
        18 : 'S',
        19 : 'T',
        20 : 'U',
        21 : 'V',
        22 : 'W',
        23 : 'X',
        24 : 'Y',
        25 : 'Z'
        }


# Labels_dict = {
#         0 : '0',
#         1 : '1',
#         2 : '2',
#         3 : '3',
#         4 : '4',
#         5 : '5',
#         6 : '6',
#         7 : '7',
#         8 : '8',
#         9 : '9',
#         }


In [4]:
import mediapipe as mp
import cv2
import numpy as np
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

In [5]:
hands = mp_hands.Hands(static_image_mode=True, min_detection_confidence=0.3)

cap = cv2.VideoCapture(0)
while (cap.isOpened()):
    
    data_aux = []
    x_ = []
    y_ = []

    ret, frame = cap.read()

    H, W, _ = frame.shape

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    results = hands.process(frame_rgb)
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame,  # image to draw
                hand_landmarks,  # model output
                mp_hands.HAND_CONNECTIONS,  # hand connections
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())

        # for hand_landmarks in results.multi_hand_landmarks:
        #     for i in range(len(hand_landmarks.landmark)):
        #         x = hand_landmarks.landmark[i].x
        #         y = hand_landmarks.landmark[i].y

        #         x_.append(x)
        #         y_.append(y)

            for i in range(len(hand_landmarks.landmark)):
                x = hand_landmarks.landmark[i].x
                y = hand_landmarks.landmark[i].y
                data_aux.append(x)
                data_aux.append(y)

        # x1 = int(min(x_) * W) - 10
        # y1 = int(min(y_) * H) - 10

        # x2 = int(max(x_) * W) - 10
        # y2 = int(max(y_) * H) - 10
        
        # print(data_aux)
        t = np.asarray(data_aux).reshape(1, 42)
        # print(t)
        # print(t.shape)
        
        prediction = np.argmax(model.predict(t), axis=1)
        # print(prediction)
        predicted_character = Labels_dict[prediction[0]]
        
        print(predicted_character)
        # cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 0, 0), 4)
        cv2.putText(frame, predicted_character, (300, 100), cv2.FONT_HERSHEY_SIMPLEX, 1.3, (255, 0, 0), 3,
                    cv2.LINE_AA)

    cv2.imshow('frame', frame)
    cv2.waitKey(1)


cap.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 303ms/step
I
1/1 [==============================] - 0s 67ms/step
E
1/1 [==============================] - 0s 64ms/step
E
1/1 [==============================] - 0s 56ms/step
E
1/1 [==============================] - 0s 70ms/step
E
1/1 [==============================] - 0s 58ms/step
E
1/1 [==============================] - 0s 65ms/step
E
1/1 [==============================] - 0s 70ms/step
E
1/1 [==============================] - 0s 68ms/step
E
1/1 [==============================] - 0s 58ms/step
E
1/1 [==============================] - 0s 63ms/step
E
1/1 [==============================] - 0s 55ms/step
I
1/1 [==============================] - 0s 59ms/step
I
1/1 [==============================] - 0s 82ms/step
I
1/1 [==============================] - 0s 66ms/step
I
1/1 [==============================] - 0s 72ms/step
I
1/1 [==============================] - 0s 70ms/step
E
1/1 [==============================] - 0s 62ms/step
E
1/1 [======================